FROM eclipse-temurin:17-jre
ENV TZ=Europe/Copenhagen \
    APP_ROOT_FOLDER=/data
WORKDIR /app
COPY build/libs/*.jar app.jar
VOLUME ["/data"]
EXPOSE 8085
ENTRYPOINT ["sh","-c","java -jar /app/app.jar"]